import { useWorkshopActions } from "./features/workshop/actions/useWorkshopActions";
import { createWorkshopHistoryHandlers } from "./features/workshop/actions/createWorkshopHistoryHandlers";
import { createWorkshopSimulationHandlers } from "./features/workshop/actions/createWorkshopSimulationHandlers";
import { createWorkshopCorrectionHandlers } from "./features/workshop/actions/createWorkshopCorrectionHandlers";
import { createWorkshopOcrConfigHandlers } from "./features/workshop/actions/createWorkshopOcrConfigHandlers";
import { createWorkshopSignalHandlers } from "./features/workshop/actions/createWorkshopSignalHandlers";
import { useWorkshopViewState } from "./features/workshop/hooks/useWorkshopViewState";
import { useWorkshopLifecycle } from "./features/workshop/hooks/useWorkshopLifecycle";
import { useWorkshopHistoryLoader } from "./features/workshop/hooks/useWorkshopHistoryLoader";
import { useWorkshopViewSyncEffects } from "./features/workshop/hooks/useWorkshopViewSyncEffects";
import { useWorkshopSimulationModels } from "./features/workshop/hooks/useWorkshopSimulationModels";
import { useWorkshopEconomyModels } from "./features/workshop/hooks/useWorkshopEconomyModels";
import { useWorkshopInsightModels } from "./features/workshop/hooks/useWorkshopInsightModels";
import { useWorkshopOcrDisplayModels } from "./features/workshop/hooks/useWorkshopOcrDisplayModels";
import { useWorkshopOcrPreviewModels } from "./features/workshop/hooks/useWorkshopOcrPreviewModels";
import { useWorkshopCatalogModels } from "./features/workshop/hooks/useWorkshopCatalogModels";
import { useWorkshopCommitRunner } from "./features/workshop/hooks/useWorkshopCommitRunner";
import { WorkshopLoadingCard, WorkshopOverviewHeader } from "./features/workshop/views/WorkshopOverviewHeader";
import { WorkshopMarketAnalysisPanel } from "./features/workshop/views/WorkshopMarketAnalysisPanel";
import { WorkshopSimulationPanel } from "./features/workshop/views/WorkshopSimulationPanel";
import { WorkshopInventoryPanel } from "./features/workshop/views/WorkshopInventoryPanel";
import { WorkshopOcrPanel } from "./features/workshop/views/WorkshopOcrPanel";
import { buildWorkshopPanelProps } from "./features/workshop/views/buildWorkshopPanelProps";
interface WorkshopViewProps {
  onJumpToHistoryManager?: (payload: { itemId: string; snapshotId?: string }) => void;
  externalPriceChangeNonce?: number;
}

export function WorkshopView(props: WorkshopViewProps = {}): JSX.Element {
  const { onJumpToHistoryManager, externalPriceChangeNonce = 0 } = props;
  const workshopActions = useWorkshopActions();
  const {
    state,
    setState,
    craftOptions,
    setCraftOptions,
    simulation,
    setSimulation,
    busy,
    setBusy,
    error,
    setError,
    message,
    setMessage,
    itemMainCategory,
    setItemMainCategory,
    itemSubCategory,
    setItemSubCategory,
    itemKeyword,
    setItemKeyword,
    selectedItemId,
    setSelectedItemId,
    selectedItemPriceMarket,
    setSelectedItemPriceMarket,
    selectedItemPrice,
    setSelectedItemPrice,
    selectedItemInventory,
    setSelectedItemInventory,
    simulateRecipeId,
    setSimulateRecipeId,
    simulateMainCategory,
    setSimulateMainCategory,
    simulateSubCategory,
    setSimulateSubCategory,
    simulateRuns,
    setSimulateRuns,
    taxMode,
    setTaxMode,
    reverseCraftBudgetInput,
    setReverseCraftBudgetInput,
    reverseMaterialKeyword,
    setReverseMaterialKeyword,
    reverseFocusMaterialId,
    setReverseFocusMaterialId,
    reverseScoreMode,
    setReverseScoreMode,
    historyItemId,
    setHistoryItemId,
    historyMainCategory,
    setHistoryMainCategory,
    historySubCategory,
    setHistorySubCategory,
    historyKeyword,
    setHistoryKeyword,
    historyDaysInput,
    setHistoryDaysInput,
    historyIncludeSuspect,
    setHistoryIncludeSuspect,
    historyServerResult,
    setHistoryServerResult,
    historyWorldResult,
    setHistoryWorldResult,
    historyHasLoaded,
    setHistoryHasLoaded,
    historyLoading,
    setHistoryLoading,
    starItemIds,
    setStarItemIds,
    focusStarOnly,
    setFocusStarOnly,
    signalRuleEnabled,
    setSignalRuleEnabled,
    signalLookbackDaysInput,
    setSignalLookbackDaysInput,
    signalThresholdPercentInput,
    setSignalThresholdPercentInput,
    signalResult,
    setSignalResult,
    ocrHotkeyShortcut,
    setOcrHotkeyShortcut,
    ocrHotkeyState,
    setOcrHotkeyState,
    ocrHotkeyLastResult,
    setOcrHotkeyLastResult,
    ocrAutoRunState,
    setOcrAutoRunState,
    ocrAutoRunIntervalSeconds,
    setOcrAutoRunIntervalSeconds,
    ocrAutoRunOverlayEnabled,
    setOcrAutoRunOverlayEnabled,
    ocrAutoRunFailLimit,
    setOcrAutoRunFailLimit,
    ocrAutoRunNowMs,
    setOcrAutoRunNowMs,
    ocrScreenPreview,
    setOcrScreenPreview,
    ocrCaptureDelayMs,
    setOcrCaptureDelayMs,
    ocrHideAppBeforeCapture,
    setOcrHideAppBeforeCapture,
    ocrSafeMode,
    setOcrSafeMode,
    ocrTradePresetKey,
    setOcrTradePresetKey,
    ocrTradeRowCount,
    setOcrTradeRowCount,
    ocrTradeNamesX,
    setOcrTradeNamesX,
    ocrTradeNamesY,
    setOcrTradeNamesY,
    ocrTradeNamesWidth,
    setOcrTradeNamesWidth,
    ocrTradeNamesHeight,
    setOcrTradeNamesHeight,
    ocrTradePricesX,
    setOcrTradePricesX,
    ocrTradePricesY,
    setOcrTradePricesY,
    ocrTradePricesWidth,
    setOcrTradePricesWidth,
    ocrTradePricesHeight,
    setOcrTradePricesHeight,
    ocrTradePriceMode,
    setOcrTradePriceMode,
    ocrTradePriceColumn,
    setOcrTradePriceColumn,
    ocrTradeLeftPriceRole,
    setOcrTradeLeftPriceRole,
    ocrTradeRightPriceRole,
    setOcrTradeRightPriceRole,
    ocrCalibrationTarget,
    setOcrCalibrationTarget,
    ocrDragStart,
    setOcrDragStart,
    ocrDragMode,
    setOcrDragMode,
    ocrDragOffset,
    setOcrDragOffset,
    ocrDragRect,
    setOcrDragRect,
    simulationMaterialDraft,
    setSimulationMaterialDraft,
    simulationOutputPriceDraft,
    setSimulationOutputPriceDraft,
    historyChartAnchorRef,
  } = useWorkshopViewState();

  const taxRate = Number(taxMode);
  const {
    starItemIdSet,
    itemById,
    classifiedItemOptions,
    starredHistoryItems,
    itemMainCategoryOptions,
    filteredItems,
    itemSubCategoryOptions,
    historyMainCategoryOptions,
    filteredHistoryItems,
    historySubCategoryOptions,
  } = useWorkshopCatalogModels({
    state,
    starItemIds,
    itemMainCategory,
    itemSubCategory,
    itemKeyword,
    historyMainCategory,
    historySubCategory,
    historyKeyword,
    focusStarOnly,
  });

  const { simulationRecipeOptions, simulationMainCategoryOptions, filteredSimulationRecipes, simulationSubCategoryOptions } =
    useWorkshopSimulationModels({
      state,
      itemById,
      simulateMainCategory,
      simulateSubCategory,
    });

  const {
    latestPriceMetaByItemId,
    inventoryByItemId,
    reverseCraftBudget,
    reverseMaterialOptions,
    reverseFocusMaterialName,
    reverseScoreModeLabel,
    reverseCraftSuggestions,
  } = useWorkshopEconomyModels({
    state,
    craftOptions,
    itemById,
    classifiedItemOptions,
    reverseCraftBudgetInput,
    reverseMaterialKeyword,
    reverseFocusMaterialId,
    reverseScoreMode,
  });
  const {
    activeHistoryQuickDays,
    historyServerInsight,
    historyWorldInsight,
    triggeredSignalRows,
    buyZoneRows,
    sellZoneRows,
    dualHistoryChartModel,
  } = useWorkshopInsightModels({
    historyDaysInput,
    historyServerResult,
    historyWorldResult,
    signalResult,
    focusStarOnly,
    starItemIdSet,
  });
  const { recentOcrImportedEntries, ocrAutoRunCountdownSeconds } = useWorkshopOcrDisplayModels({
    ocrHotkeyLastResult,
    ocrAutoRunState,
    ocrAutoRunNowMs,
  });

  const { ocrTradeNamesRect, ocrTradePricesRect, onPreviewMouseDown, onPreviewMouseMove, onPreviewMouseUp } =
    useWorkshopOcrPreviewModels({
      ocrTradePresetKey,
      ocrCalibrationTarget,
      ocrTradeNamesX,
      ocrTradeNamesY,
      ocrTradeNamesWidth,
      ocrTradeNamesHeight,
      ocrTradePricesX,
      ocrTradePricesY,
      ocrTradePricesWidth,
      ocrTradePricesHeight,
      ocrDragMode,
      ocrDragOffset,
      ocrDragStart,
      ocrDragRect,
      ocrScreenPreview,
      setOcrTradePresetKey,
      setOcrTradeNamesX,
      setOcrTradeNamesY,
      setOcrTradeNamesWidth,
      setOcrTradeNamesHeight,
      setOcrTradePricesX,
      setOcrTradePricesY,
      setOcrTradePricesWidth,
      setOcrTradePricesHeight,
      setOcrDragMode,
      setOcrDragOffset,
      setOcrDragStart,
      setOcrDragRect,
    });
  const { loadState, loadCraftOptions, loadSignals } = useWorkshopLifecycle({
    workshopActions,
    taxRate,
    setState,
    setCraftOptions,
    setSignalResult,
    setBusy,
    setError,
    setMessage,
    setOcrHotkeyState,
    setOcrHotkeyShortcut,
    setOcrHotkeyLastResult,
    setOcrAutoRunState,
    setOcrAutoRunIntervalSeconds,
    setOcrAutoRunOverlayEnabled,
    setOcrAutoRunFailLimit,
  });
  const { commit } = useWorkshopCommitRunner({
    setBusy,
    setError,
    setMessage,
    setState,
    loadCraftOptions,
    loadSignals,
  });

  useWorkshopViewSyncEffects({
    itemMainCategory,
    itemMainCategoryOptions,
    itemSubCategory,
    itemSubCategoryOptions,
    selectedItemId,
    filteredItems,
    setItemMainCategory,
    setItemSubCategory,
    setSelectedItemId,
    historyMainCategory,
    historyMainCategoryOptions,
    historySubCategory,
    historySubCategoryOptions,
    historyItemId,
    filteredHistoryItems,
    setHistoryMainCategory,
    setHistorySubCategory,
    setHistoryItemId,
    setHistoryServerResult,
    setHistoryWorldResult,
    setHistoryHasLoaded,
    simulateMainCategory,
    simulationMainCategoryOptions,
    simulateSubCategory,
    simulationSubCategoryOptions,
    simulateRecipeId,
    filteredSimulationRecipes,
    setSimulateMainCategory,
    setSimulateSubCategory,
    setSimulateRecipeId,
    setSimulation,
    setSimulationOutputPriceDraft,
    reverseFocusMaterialId,
    classifiedItemOptions,
    setReverseFocusMaterialId,
    state,
    setSignalRuleEnabled,
    setSignalLookbackDaysInput,
    setSignalThresholdPercentInput,
    selectedItemPriceMarket,
    latestPriceMetaByItemId,
    inventoryByItemId,
    setSelectedItemPrice,
    setSelectedItemInventory,
    taxMode,
    loadCraftOptions,
    ocrTradePresetKey,
    setOcrTradeRowCount,
    setOcrTradeNamesX,
    setOcrTradeNamesY,
    setOcrTradeNamesWidth,
    setOcrTradeNamesHeight,
    setOcrTradePricesX,
    setOcrTradePricesY,
    setOcrTradePricesWidth,
    setOcrTradePricesHeight,
    setOcrTradePriceMode,
    setOcrTradePriceColumn,
    setOcrTradeLeftPriceRole,
    setOcrTradeRightPriceRole,
    starItemIds,
    setStarItemIds,
    ocrAutoRunState,
    setOcrAutoRunNowMs,
  });

  const { onLoadPriceHistory } = useWorkshopHistoryLoader({
    workshopActions,
    historyItemId,
    historyDaysInput,
    historyIncludeSuspect,
    externalPriceChangeNonce,
    loadState,
    loadCraftOptions,
    loadSignals,
    setError,
    setHistoryLoading,
    setHistoryServerResult,
    setHistoryWorldResult,
    setHistoryHasLoaded,
  });

  function isStarredItem(itemId: string): boolean {
    return starItemIdSet.has(itemId);
  }

  const {
    onToggleStarItem,
    onJumpHistoryManagerForCurrentItem,
    onJumpHistoryManagerForSnapshot,
    onViewHistoryCurveForItem,
  } = createWorkshopHistoryHandlers({
    historyItemId,
    historyDaysInput,
    starItemIdSet,
    itemById,
    classifiedItemOptions,
    onLoadPriceHistory,
    onJumpToHistoryManager,
    setSelectedItemPriceMarket,
    setHistoryKeyword,
    setHistoryMainCategory,
    setHistorySubCategory,
    setHistoryItemId,
    setStarItemIds,
    setError,
    setMessage,
    historyChartAnchorRef,
  });
  const { onJumpSimulationRecipe, onSimulate, onApplySimulationMaterialEdits } = createWorkshopSimulationHandlers({
    simulateRecipeId,
    simulateRuns,
    taxRate,
    simulation,
    simulationRecipeOptions,
    simulationMaterialDraft,
    simulationOutputPriceDraft,
    workshopActions,
    setBusy,
    setError,
    setMessage,
    setState,
    setSimulation,
    setSimulationMaterialDraft,
    setSimulationOutputPriceDraft,
    setSimulateMainCategory,
    setSimulateSubCategory,
    setSimulateRecipeId,
    loadCraftOptions,
    loadSignals,
  });
  const { onSaveSelectedPrice, onSaveSelectedInventory, onPickItemForCorrection } = createWorkshopCorrectionHandlers({
    selectedItemId,
    selectedItemPrice,
    selectedItemInventory,
    selectedItemPriceMarket,
    latestPriceMetaByItemId,
    inventoryByItemId,
    workshopActions,
    commit,
    setError,
    setSelectedItemId,
    setSelectedItemPrice,
    setSelectedItemInventory,
  });
  const { onApplyOcrHotkeyConfig, onTriggerOcrHotkeyNow, onCaptureOcrScreenPreview, onConfigureOcrAutoRun } =
    createWorkshopOcrConfigHandlers({
      ocrTradeRowCount,
      ocrTradeNamesX,
      ocrTradeNamesY,
      ocrTradeNamesWidth,
      ocrTradeNamesHeight,
      ocrTradePricesX,
      ocrTradePricesY,
      ocrTradePricesWidth,
      ocrTradePricesHeight,
      ocrTradePriceMode,
      ocrTradePriceColumn,
      ocrTradeLeftPriceRole,
      ocrTradeRightPriceRole,
      ocrHotkeyShortcut,
      ocrSafeMode,
      ocrCaptureDelayMs,
      ocrHideAppBeforeCapture,
      ocrAutoRunIntervalSeconds,
      ocrAutoRunFailLimit,
      ocrAutoRunOverlayEnabled,
      workshopActions,
      loadState,
      loadCraftOptions,
      loadSignals,
      setBusy,
      setError,
      setMessage,
      setOcrHotkeyState,
      setOcrHotkeyShortcut,
      setOcrSafeMode,
      setOcrHotkeyLastResult,
      setOcrScreenPreview,
      setOcrAutoRunState,
      setOcrAutoRunIntervalSeconds,
      setOcrAutoRunOverlayEnabled,
      setOcrAutoRunFailLimit,
    });
  const { onSaveSignalRule, onRefreshSignals } = createWorkshopSignalHandlers({
    signalLookbackDaysInput,
    signalThresholdPercentInput,
    signalRuleEnabled,
    workshopActions,
    commit,
    loadSignals,
    setBusy,
    setError,
    setMessage,
  });

  if (!state) {
    return <WorkshopLoadingCard />;
  }

  const { ocrPanelProps, marketAnalysisPanelProps, simulationPanelProps, inventoryPanelProps } = buildWorkshopPanelProps({
    busy,
    ocrPanelProps: {
      ocrCaptureDelayMs,
      setOcrCaptureDelayMs,
      ocrHideAppBeforeCapture,
      setOcrHideAppBeforeCapture,
      ocrSafeMode,
      setOcrSafeMode,
      ocrHotkeyShortcut,
      setOcrHotkeyShortcut,
      onApplyOcrHotkeyConfig,
      onTriggerOcrHotkeyNow,
      ocrAutoRunIntervalSeconds,
      setOcrAutoRunIntervalSeconds,
      ocrAutoRunFailLimit,
      setOcrAutoRunFailLimit,
      ocrAutoRunOverlayEnabled,
      setOcrAutoRunOverlayEnabled,
      onConfigureOcrAutoRun,
      ocrAutoRunState,
      ocrAutoRunCountdownSeconds,
      ocrHotkeyState,
      ocrHotkeyLastResult,
      ocrTradePresetKey,
      setOcrTradePresetKey,
      ocrCalibrationTarget,
      setOcrCalibrationTarget,
      ocrTradeRowCount,
      setOcrTradeRowCount,
      onCaptureOcrScreenPreview,
      ocrScreenPreview,
      onPreviewMouseDown,
      onPreviewMouseMove,
      onPreviewMouseUp,
      ocrTradeNamesRect,
      ocrTradePricesRect,
      ocrDragRect,
    },
    marketAnalysisPanelProps: {
      historyMainCategory,
      setHistoryMainCategory,
      historyMainCategoryOptions,
      historySubCategory,
      setHistorySubCategory,
      historySubCategoryOptions,
      historyKeyword,
      setHistoryKeyword,
      historyItemId,
      setHistoryItemId,
      filteredHistoryItems,
      historyDaysInput,
      setHistoryDaysInput,
      onJumpHistoryManagerForCurrentItem,
      onToggleStarItem,
      isStarredItem,
      focusStarOnly,
      setFocusStarOnly,
      starredHistoryItems,
      onViewHistoryCurveForItem,
      historyIncludeSuspect,
      setHistoryIncludeSuspect,
      activeHistoryQuickDays,
      recentOcrImportedEntries,
      historyChartAnchorRef,
      historyLoading,
      historyHasLoaded,
      historyServerResult,
      historyWorldResult,
      dualHistoryChartModel,
      onJumpHistoryManagerForSnapshot,
      historyServerInsight,
      historyWorldInsight,
      signalRuleEnabled,
      setSignalRuleEnabled,
      signalLookbackDaysInput,
      setSignalLookbackDaysInput,
      signalThresholdPercentInput,
      setSignalThresholdPercentInput,
      onSaveSignalRule,
      onRefreshSignals,
      signalResult,
      triggeredSignalRows,
      buyZoneRows,
      sellZoneRows,
    },
    simulationPanelProps: {
      simulation,
      onApplySimulationMaterialEdits,
      simulateMainCategory,
      setSimulateMainCategory,
      simulationMainCategoryOptions,
      simulateSubCategory,
      setSimulateSubCategory,
      simulationSubCategoryOptions,
      simulateRecipeId,
      setSimulateRecipeId,
      filteredSimulationRecipes,
      simulateRuns,
      setSimulateRuns,
      simulationOutputPriceDraft,
      setSimulationOutputPriceDraft,
      taxMode,
      setTaxMode,
      onSimulate,
      resolveItemName: (itemId) => itemById.get(itemId)?.name ?? itemId,
      simulationMaterialDraft,
      setSimulationMaterialDraft,
    },
    inventoryPanelProps: {
      loadCraftOptions,
      itemKeyword,
      setItemKeyword,
      itemMainCategory,
      setItemMainCategory,
      itemMainCategoryOptions,
      itemSubCategory,
      setItemSubCategory,
      itemSubCategoryOptions,
      selectedItemId,
      setSelectedItemId,
      filteredItems,
      selectedItemPriceMarket,
      setSelectedItemPriceMarket,
      selectedItemPrice,
      setSelectedItemPrice,
      selectedItemInventory,
      setSelectedItemInventory,
      onSaveSelectedPrice,
      onSaveSelectedInventory,
      latestPriceMetaByItemId,
      inventoryByItemId,
      onPickItemForCorrection,
      reverseMaterialKeyword,
      setReverseMaterialKeyword,
      reverseFocusMaterialId,
      setReverseFocusMaterialId,
      reverseMaterialOptions,
      reverseCraftBudgetInput,
      setReverseCraftBudgetInput,
      reverseScoreMode,
      setReverseScoreMode,
      reverseFocusMaterialName,
      reverseCraftBudget,
      reverseScoreModeLabel,
      craftOptions,
      reverseCraftSuggestions,
      isStarredItem,
      onToggleStarItem,
      onViewHistoryCurveForItem,
      onJumpSimulationRecipe,
    },
  });

  return (
    <div className="flex flex-col gap-4">
      <WorkshopOverviewHeader state={state} starCount={starItemIds.length} message={message} error={error} />

      <WorkshopOcrPanel {...ocrPanelProps} />
      <WorkshopMarketAnalysisPanel {...marketAnalysisPanelProps} />
      <WorkshopSimulationPanel {...simulationPanelProps} />
      <WorkshopInventoryPanel {...inventoryPanelProps} />
    </div>
  );
}

