export const IPC_CHANNELS = {
  getState: "app:get-state",
  getBuildInfo: "app:get-build-info",
  resetWeeklyStats: "app:reset-weekly-stats",
  undoOperations: "app:undo-operations",
  clearHistory: "app:clear-history",
  updateSettings: "app:update-settings",
  exportData: "app:export-data",
  importData: "app:import-data",
  addAccount: "account:add",
  renameAccount: "account:rename",
  deleteAccount: "account:delete",
  selectAccount: "account:select",
  addCharacter: "character:add",
  renameCharacter: "character:rename",
  deleteCharacter: "character:delete",
  selectCharacter: "character:select",
  applyTaskAction: "task:apply-action",
  updateArtifactStatus: "character:update-artifact",
  applyCorridorCompletion: "character:apply-corridor-completion",
  updateEnergySegments: "character:update-energy-segments",
  updateRaidCounts: "character:update-raid-counts",
  updateWeeklyCompletions: "character:update-weekly-completions",
  updateAodePlan: "character:update-aode-plan",
} as const;
